### ISSUE TITLE
A few suggestions for code improvements

### ISSUE THREAD

**Issue by sdrapkin** [YuriyIvon/DatabaseBenchmark#1]
Since you build for .NET6, in [`RandomGenerator.cs`](https://github.com/YuriyIvon/DatabaseBenchmark/blob/main/src/DatabaseBenchmark/Core/RandomGenerator.cs) switch to 
```csharp
readonly Random _random = Random.Shared;
```

[`MemoryCache.cs`](https://github.com/YuriyIvon/DatabaseBenchmark/blob/main/src/DatabaseBenchmark/Core/MemoryCache.cs) switch to `ConcurrentDictionary` instead.

[`QueryBenchmark.cs`](https://github.com/YuriyIvon/DatabaseBenchmark/blob/main/src/DatabaseBenchmark/Core/QueryBenchmark.cs) switch to `DateTime.UtcNow`.

**Comment by YuriyIvon** [comment]
Thanks, I've applied Random.Shared and UtcNow. As for ConcurrentDictionary - the lock in the MemoryCache class is intentional - all threads asking the same set of distinct values must wait until the first one fetches them from the database. I am going to refactor this piece in the future to make it more optimal, but for now it does the job.
